### PR TITLE
Compound supply and redeeem

### PR DESCRIPTION
**Pull request by 0xA1176ec01045**
Aztec connect bridge for `supply` or `redeem` on any Compound cToken contract.
- `auxData` is used to toggle between actions (currently limited to `supply`/`redeem`). `redeemUnderlying` is not implemented, so redeem actions expect a number of cTokens, not a number of underlying tokens to retrieve.
- Could have used cToken `isCToken()` function to determine the proper action without `auxData`, but a toggle will be necessary anyway for future extension to borrow/repay actions.
- Includes supply and redeem tests, some with specific deposit/withdrawal values, others fuzzed; at least one action is tested on every cToken.
- Primitive bridge data script is provided in the client/ folder; it is untested and likely needs additional work.

### CODE REVIEW

**Comment by joeandrews** [comment]
Hi @0xA1176ec01045 Thanks for this. Would you be able to fix the merge conflicts and remove the WIP bridge-data class so we can merge the solidity file in? Excited to get this working!

We can do a separate PR for the bridge-data when it is ready. On this would a call be helpful?

**Comment by 0xA1176ec01045** [comment]
Thanks for the call today. The CI failure here seems to have pre-existed this commit; otherwise the bridge contract should be ready for review. I'll get a separate PR going for the bridge-data when ready.

**Comment by joeandrews** [comment]
@0xA1176ec01045  Can you resolve these conflicts so we can get this merged. Looking forward to it!

**Comment by 0xA1176ec01045** [comment]
Yes! Last time I managed to resolve the conflicts without issue, but this time I'm not sure how to work around the (hundreds of) differences that have recently appeared in yarn.lock. [This guidance](https://gist.github.com/RadValentin/226550d8b90133cfc77519771a03f340) looked helpful but didn't have the intended effect. Any other suggestions for how to resolve the conflicts in yarn.lock?

**Comment by 0xA1176ec01045** [comment]
I've decided to start over with a new PR off a fresh copy of the repo, adding and testing my changes. Everything looks good, my only issue now is that I'm running into a permissions issue when I try to submit the new PR. It's [this issue here](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-to-userrepo-denied-to-other-user), so maybe if you could add my github account 0xA1776ec01045 to the repo, we can get this moving forward again :)

**Comment by 0xA1176ec01045** [comment]
Closing this PR; superseded by PR #38

**Pull request closed without merging**
