### PR TITLE
Liquity bridges

### PR DESCRIPTION
**Pull request by benesjan**
This PR contains implementions of the bridges for Liquity's stability pool, LQTY staking contract and troves.

All the tests are passing but for them to pass I had to replace the provided Infura endpoint with my own. I think the provided endpoint is being rate limited.

Screen Shot 2022-02-08 at 12 31 58
.

To make my contracts work I had to do some changes out of my codebase:
1) I renamed WETH to IWETH in the IWETH.sol file. I checked and this change didn't affect any other code.
2) I removed SafeMath dependency from DefiBridgeProxy.sol and MockRollupProcessor.sol since it was causing errors in my code. The code is in Solidity ^0.8.0 so SafeMath is not necessary anymore.

I did gas profiling and these are the average results on the most important functions:

StabilityPoolBridge.convert(...): 503389 gas
StakingBridge.convert(...): 127544 gas
TroveBridge.convert(...): 145223 gas

### CODE REVIEW

**Comment by joeandrews** [comment]
Thanks for this Jan! We are reviewing and aim to merge next week.

**Comment by joeandrews** [comment]
@benesjan Could you close this and re-open this so the new CI runs?

**Comment by benesjan** [comment]
> @benesjan Could you close this and re-open this so the new CI runs?

I just closed and reopened the PR but the CI didn't seem to run.

**Comment by joeandrews** [comment]
> > @benesjan Could you close this and re-open this so the new CI runs?
> 
> @joeandrews I just closed and reopened the PR but the CI didn't seem to run.

Can you push a new commit? I think it only runs when you create a new PR. I will dig in further.

**Comment by joeandrews** [comment]
Okay I forced the tests to run, can you rebase from master and push, then the tests should pass :)

**Comment by benesjan** [comment]
> Okay I forced the tests to run, can you rebase from master and push, then the tests should pass :)

I just rebased and pushed the branch :)

**Pull request closed without merging**
