### PR TITLE
[WIP] Add Ribbon Finance bridge contract

### PR DESCRIPTION
**Pull request by drshrey**

### CODE REVIEW

**Comment by benesjan** [comment]
Hello @drshrey, how is it going with this bridge? 😊

**Comment by drshrey** [comment]
Finishing up the final unit test and finalise logic today, will have it out for the first set of reviews eod PT!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by benesjan** [comment]
> Finishing up the final unit test and finalise logic today, will have it out for the first set of reviews eod PT!

Great to hear 👍 

BTW can you please rebase the branch onto master and fix the linting errors in your code (if there are some)? Lately we've done many changes to the code quality requirements so would it be great to have this branch follow that.

We updated dependencies so before running tests don't forget to run `yarn and `git submodule update --init` again.

Thank you

**Comment by drshrey** [comment]
Rebased! @benesjan, one final question I had was around the finalization process for withdrawals. There are 2 withdrawal processes, but the tricky one seems to be the asynchronous one i.e. there is effectively a 1 hour window between rounds in which we can complete a withdrawal request for tokens posted in prior rounds. Is there a way for the rollup processor to invoke `finalise()` during that time window (Fridays at 10 AM UTC)?

**Comment by LHerskind** [comment]
> Rebased! @benesjan, one final question I had was around the finalization process for withdrawals. There are 2 withdrawal processes, but the tricky one seems to be the asynchronous one i.e. there is effectively a 1 hour window between rounds in which we can complete a withdrawal request for tokens posted in prior rounds (we do have to initialize the request beforehand which has more leniency on when). Is there a way for the rollup processor to invoke `finalise()` during that time window (Fridays between 10 AM - 11 AM UTC)?

Hi, for the asynchronous execution, anyone is able to go to the `RollupProcessor` to call `processAsyncDefiInteraction` with the specific nonce, so you might want to think about a manner to ensure that someone performs this call, e.g., cover the gas cost etc. If you want to do it from within a rollup itself, you might not hit the correct timing. Let me know if you got any questions.

**Comment by benesjan** [comment]
@drshrey It seems that the contracts don't compile. Can you please fix that along with the linting errors? Running `yarn lint` returns the following:
Screen Shot 2022-05-31 at 22 29 00

Thank you 👍

**Pull request closed without merging**
